### ISSUE TITLE
docker全功能部署遇到websocket无法配置地址

### ISSUE THREAD

**Issue by Cmdmac** [xinnan-tech/xiaozhi-esp32-server#1013]
## 🐛 问题描述
docker全功能部署遇到websocket无法配置地址，有如下日志,，请问是安装问题吗，我把model.pt删除了也不行，这个不是安装的时候手动拉下来的吗：
Traceback (most recent call last):
  File "/opt/xiaozhi-esp32-server/app.py", line 53, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/xiaozhi-esp32-server/app.py", line 35, in main
    ws_server = WebSocketServer(config)
  File "/opt/xiaozhi-esp32-server/core/websocket_server.py", line 14, in __init__
    modules = initialize_modules(
  File "/opt/xiaozhi-esp32-server/core/utils/util.py", line 320, in initialize_modules
    modules["asr"] = asr.create_instance(
  File "/opt/xiaozhi-esp32-server/core/utils/asr.py", line 22, in create_instance
    return sys.modules[lib_name].ASRProvider(*args, **kwargs)
  File "/opt/xiaozhi-esp32-server/core/providers/asr/fun_local.py", line 45, in __init__
    self.model = AutoModel(
  File "/usr/local/lib/python3.10/site-packages/funasr/auto/auto_model.py", line 125, in __init__
    model, kwargs = self.build_model(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/funasr/auto/auto_model.py", line 270, in build_model
    load_pretrained_model(
  File "/usr/local/lib/python3.10/site-packages/funasr/train_utils/load_pretrained_model.py", line 39, in load_pretrained_model
    ori_state = torch.load(path, map_location=map_location)
  File "/usr/local/lib/python3.10/site-packages/torch/serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.10/site-packages/torch/serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.10/site-packages/torch/serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
IsADirectoryError: [Errno 21] Is a directory: 'models/SenseVoiceSmall/model.pt'
250426 22:17:43[0.3.11-VAASLLTTMeIn][core.utils.util]-INFO-初始化组件: tts成功 TTS_EdgeTTS
250426 22:17:44[0.3.11-VAASLLTTMeIn][core.utils.util]-INFO-初始化组件: llm成功 LLM_CozeLLM
250426 22:17:45[0.3.11-VAASLLTTMeIn][core.utils.util]-INFO-初始化组件: intent成功 Intent_function_call
250426 22:17:45[0.3.11-VAASLLTTMeIn][core.utils.util]-INFO-初始化组件: memory成功 Memory_nomem
250426 22:17:51[0.3.11-VAASLLTTMeIn][core.providers.vad.silero]-INFO-SileroVAD
250426 22:17:53[0.3.11-VAASLLTTMeIn][core.utils.util]-INFO-初始化组件: vad成功 VAD_SileroVAD

250426 22:18:26[0.3.11-VAASLLTTMeIn][core.providers.asr.fun_local]-INFO-funasr version: 1.2.3.
Traceback (most recent call last):
  File "/opt/xiaozhi-esp32-server/app.py", line 53, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/opt/xiaozhi-esp32-server/app.py", line 35, in main
    ws_server = WebSocketServer(config)
  File "/opt/xiaozhi-esp32-server/core/websocket_server.py", line 14, in __init__
    modules = initialize_modules(
  File "/opt/xiaozhi-esp32-server/core/utils/util.py", line 320, in initialize_modules
    modules["asr"] = asr.create_instance(
  File "/opt/xiaozhi-esp32-server/core/utils/asr.py", line 22, in create_instance
    return sys.modules[lib_name].ASRProvider(*args, **kwargs)
  File "/opt/xiaozhi-esp32-server/core/providers/asr/fun_local.py", line 45, in __init__
    self.model = AutoModel(
  File "/usr/local/lib/python3.10/site-packages/funasr/auto/auto_model.py", line 125, in __init__
    model, kwargs = self.build_model(**kwargs)
  File "/usr/local/lib/python3.10/site-packages/funasr/auto/auto_model.py", line 270, in build_model
    load_pretrained_model(
  File "/usr/local/lib/python3.10/site-packages/funasr/train_utils/load_pretrained_model.py", line 39, in load_pretrained_model
    ori_state = torch.load(path, map_location=map_location)
  File "/usr/local/lib/python3.10/site-packages/torch/serialization.py", line 998, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/usr/local/lib/python3.10/site-packages/torch/serialization.py", line 445, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/usr/local/lib/python3.10/site-packages/torch/serialization.py", line 426, in __init__
    super().__init__(open(name, mode))
IsADirectoryError: [Errno 21] Is a directory: 'models/SenseVoiceSmall/model.pt'

## 🖥️ 环境信息
- 操作系统: nanopi r5s openwrt

**Comment by openrz** [comment]
给我看一下你的目录结构，正常来说是这样的：
```
xiaozhi-server
  ├─ docker-compose.yml
  ├─ data
    ├─ .config.yaml
  ├─ models
     ├─ SenseVoiceSmall
       ├─ model.pt
```

**Comment by Cmdmac** [comment]
目录结构确认了，是对的，我把model.pt目录删除了，再重新手动下载mode.pt后，重启docker出现这个错误
Error response from daemon: Cannot restart container xiaozhi-esp32-server: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error mounting "/mnt/sdcard/xiaozhi-server/models/SenseVoiceSmall/model.pt" to rootfs at "/opt/xiaozhi-esp32-server/models/SenseVoiceSmall/model.pt": mount /mnt/sdcard/xiaozhi-server/models/SenseVoiceSmall/model.pt:/opt/xiaozhi-esp32-server/models/SenseVoiceSmall/model.pt (via /proc/self/fd/6), flags: 0x5000: not a directory: unknown: Are you trying to mount a directory onto a file (or vice-versa)? Check if the specified host path exists and is the expected type

**Comment by openrz** [comment]
把你的docker-compose发上来看一下

**Comment by Cmdmac** [comment]
就是按教程执行命令下载的wget https://raw.githubusercontent.com/xinnan-tech/xiaozhi-esp32-server/refs/heads/main/main/xiaozhi-server/docker-compose_all.yml


```

# Docker安装全模块

version: '3'
services:
  # Server模块
  xiaozhi-esp32-server:
    image: ghcr.nju.edu.cn/xinnan-tech/xiaozhi-esp32-server:server_latest
    container_name: xiaozhi-esp32-server
    depends_on:
      - xiaozhi-esp32-server-db
      - xiaozhi-esp32-server-redis
    restart: always
    networks:
      - default
    ports:
      # ws服务端
      - "8000:8000"
    security_opt:
      - seccomp:unconfined
    environment:
      - TZ=Asia/Shanghai
    volumes:
      # 配置文件目录
      - ./data:/opt/xiaozhi-esp32-server/data
      # 模型文件挂接，很重要
      - ./models/SenseVoiceSmall/model.pt:/opt/xiaozhi-esp32-server/models/SenseVoiceSmall/model.pt

  # manager-api和manager-web模块
  xiaozhi-esp32-server-web:
    image: ghcr.nju.edu.cn/xinnan-tech/xiaozhi-esp32-server:web_latest
    container_name: xiaozhi-esp32-server-web
    restart: always
    networks:
      - default
    depends_on:
      xiaozhi-esp32-server-db:
        condition: service_healthy
      xiaozhi-esp32-server-redis:
        condition: service_healthy
    ports:
      # 智控台
      - "8002:8002"
    environment:
      - TZ=Asia/Shanghai
      - SPRING_DATASOURCE_DRUID_URL=jdbc:mysql://xiaozhi-esp32-server-db:3306/xiaozhi_esp32_server?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&nullCatalogMeansCurrent=true&connectTimeout=30000&socketTimeout=30000&autoReconnect=true&failOverReadOnly=false&maxReconnects=10
      - SPRING_DATASOURCE_DRUID_USERNAME=root
      - SPRING_DATASOURCE_DRUID_PASSWORD=123456
      - SPRING_DATA_REDIS_HOST=xiaozhi-esp32-server-redis
      - SPRING_DATA_REDIS_PORT=6379
    volumes:
      # 配置文件目录
      - ./uploadfile:/app/uploadfile

  xiaozhi-esp32-server-db:
    image: mysql:latest
    container_name: xiaozhi-esp32-server-db
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    networks:
      - default
    expose:
      - 3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
      - TZ=Asia/Shanghai
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=xiaozhi_esp32_server
      - MYSQL_INITDB_ARGS="--character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci"
  xiaozhi-esp32-server-redis:
    image: redis
    expose:
      - 6379
    container_name: xiaozhi-esp32-server-redis
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - default
networks:
  default:

```
