### ISSUE TITLE
怎么增加聆听时长呢？

### ISSUE THREAD

**Issue by 6666665** [xinnan-tech/xiaozhi-esp32-server#1217]
我的小智设备 好像聆听一秒就开始讲话了。想问下哪里可以设置时长 感谢！！！！

**Comment by openrz** [comment]
是每次你说话，他都会很着急的主动打断你吗？

**Comment by 6666665** [comment]
> 是每次你说话，他都会很着急的主动打断你吗？

是的  我讲话后 一秒差不多 他就开始回复我了。 我不讲话他会一直聆听

**Comment by openrz** [comment]
```
VAD:
  SileroVAD:
    type: silero
    threshold: 0.5
    model_dir: models/snakers4_silero-vad
    min_silence_duration_ms: 700  # 如果说话停顿比较长，可以把这个值设置大一些
```
试试看，把min_silence_duration_ms设置成1300
