### ISSUE TITLE
在阿里服务器部署简单的server，用的conda本地部署，在data的.config.yaml设置的公网ip

### ISSUE THREAD

**Issue by mypy98** [xinnan-tech/xiaozhi-esp32-server#1338]
阿里云服务器在运行python app.py后输出的不是公网的地址，是本地地址，无法用test.html访问

**Comment by openrz** [comment]
输出的地址不是公网地址没关系，但是你要用浏览器访问一下你的ota接口，看看下发到esp32的地址是不是公网地址，如果不是公网地址，你要在配置文件里改一下`server.websocket`。配完后重启xiaozhi-server
```
server:
  # 服务器监听地址和端口(Server listening address and port)
  ip: 0.0.0.0
  port: 8000
  # OTA接口的端口号
  ota_port: 8002
  # 这个websocket配置是指ota接口向设备发送的websocket地址
  # 如果按默认的写法，ota接口会自动生成websocket地址。这个地址你可以直接用浏览器访问ota接口确认一下
  # 当你使用docker部署或使用公网部署(使用ssl、域名)时，不一定准确
  # 所以如果你使用docker部署或使用公网部署时，请设置正确的websocket地址
  websocket: ws://你的ip或者域名:端口号/xiaozhi/v1/
```
