### ISSUE TITLE
docker compose升级0.5.6后server端日志异常

### ISSUE THREAD

**Issue by zuoluoonevip** [xinnan-tech/xiaozhi-esp32-server#1603]
![Image](https://github.com/user-attachments/assets/bf2855bf-31d4-4bf6-9f20-67a46f783118)

**Comment by openrz** [comment]
你的配置文件缺了这些配置，可以下载[最新的配置文件](https://github.com/xinnan-tech/xiaozhi-esp32-server/blob/main/main/xiaozhi-server/config_from_api.yaml)补全
```
server:
  ip: 0.0.0.0
  port: 8000
  http_port: 8003
  # 视觉分析接口地址
  vision_explain: http://你的ip或者域名:端口号/mcp/vision/explain
```
