### ISSUE TITLE
部署问题请教

### ISSUE THREAD

**Issue by jlau-ice** [xinnan-tech/xiaozhi-esp32-server#1668]
我现在部署在内网服务器上，申请 OTA 之地为公网域名。通过外网我能连接上manager-api，但是无法连接服务端xiaozhi-server,  需要开放 wbsocket 地址吗，或者其他的端口地址。

**Comment by openrz** [comment]
要看你部署的策略。
如果你用到了nginx，可以使用nginx将他们整合在一个端口里。参考我的nginx配置 #791 
如果你没有用到nginx，你就要8000-8004端口都开放了。

**Comment by jlau-ice** [comment]
我參考了你的nginx 配置，好像没有转发成功。
我开放的是 manager-api 的端口 8004（容器里面是8002）
8001 是manager-web 的地址。
前端websocket参数 改成  8001 测试是可以联通的
![Image](https://github.com/user-attachments/assets/b34edfcf-23ed-46c6-95f9-b5a95a770bb0)
但是改完 询问小智还是连接中，您看看我写的，哪里还有问题吗
```
#user  nobody;
worker_processes  1;
#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;

events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
    client_max_body_size 200M;
    server {
        listen       8001;
        listen [::]:8001;
        server_name _;
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        location /xiaozhi/ {
            set $method $request_method;
            if ($http_X_HTTP_Method_Override ~* 'PUT|DELETE') {
                set $method $http_X_HTTP_Method_Override;
            }
            proxy_method $method;
            proxy_pass http://xiaozhi-server:8002/xiaozhi/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # 转发到xiaozhi-server到websocket
        location /xiaozhi/v1/ {
            proxy_pass http://192.168.187.166:8000;
            proxy_set_header Host $host;
            proxy_cookie_path /xiaozhi/ /;

            # 核心IP转发配置
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # WebSocket支持（保持原有配置）
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            # 其他头信息（可选）
            proxy_set_header Referer $http_referer;
            proxy_set_header Cookie $http_cookie;
        }
        # mcp相关请求
        location /mcp/ {
            proxy_pass http://192.168.187.166:8000;
            proxy_set_header   Host   $host;
            proxy_cookie_path /mcp/ /;
            proxy_set_header   Referer $http_referer;
            proxy_set_header   Cookie $http_cookie;

            proxy_connect_timeout 15;
            proxy_send_timeout 15;
            proxy_read_timeout 15;

            proxy_set_header   X-Real-IP  $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        }
    }
}

```

**Comment by openrz** [comment]
<img width="492" alt="Image" src="https://github.com/user-attachments/assets/1f427de6-1f39-4b30-85fc-9f29fe7d241f" />

**Comment by jlau-ice** [comment]
编译后的目录是对的，这部分可以正常访问
![Image](https://github.com/user-attachments/assets/469b3a60-6dae-47fc-bc13-f67001a25b91)
这里容器名是 xiaozhi-server （这个其实是manager-api java后端，个人命名习惯哈哈， xiaozhi-server 是源码启动的，没有用容器 ），前后端是可以正常交互的
![Image](https://github.com/user-attachments/assets/8574e4ca-9e4f-49ef-80f9-fc90fa635e86)
mcp 这里也修改了
![Image](https://github.com/user-attachments/assets/098cc3d2-1315-4eff-8821-3b4f127a893b)
控制台，这里是可以连接上设备的。
![Image](https://github.com/user-attachments/assets/5a0effc2-25ab-42d6-aeeb-edcf47a46e60)
但是好像无法连接 xiaoshi-server 端 
![Image](https://github.com/user-attachments/assets/1662ee74-5b38-4023-8e67-66f0b4be9766)
我的docker-compose.yml 是这样的 
```
## 前后端 + 数据库 + redis 服务端源码启动 
services:
  web:
    image: nginx:latest
    container_name: xiaozhi-web
    ports:
      - "8001:8001"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/dist:/usr/share/nginx/html
    depends_on:
      - server
    restart: always
    networks:
      - xiaozhi-net
      
  server:
    image: openjdk:21-jdk
    container_name: xiaozhi-server
    volumes:
      - ./server/xiaozhi-esp32-api.jar:/app.jar
      - ./server/logs:/logs
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8004:8002"
    entrypoint:
      - /bin/sh
      - -c
      - |
        mkdir -p /logs && \
        java -jar app.jar | tee /logs/server.log
    restart: always
    networks:
      - xiaozhi-net

  redis:
    image: redis:latest
    container_name: xiaozhi-redis
    ports:
      - "6381:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    networks:
      - xiaozhi-net

  mysql:
    image: mysql8:latest
    container_name: xiaozhi-mysql
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "123456"
    volumes:

      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/my.cnf
    restart: always
    networks:
      - xiaozhi-net

networks:
  xiaozhi-net:
    external: true
```

**Comment by openrz** [comment]
看看8000启动了吗？

**Comment by jlau-ice** [comment]
启动了，使用公司内网是可以正常使用的，用外网不行。
![Image](https://github.com/user-attachments/assets/6cb3cb2e-1fa9-4b87-a112-b318834379d0)

**Comment by openrz** [comment]
是不是公司的防火墙挡住了websocket协议的连接？

**Comment by jlau-ice** [comment]
您好，请问有 设备、manager-api、xiaozhi-server  三端通讯的原理图吗，我想知道他们三是怎么通讯的。

**Comment by jlau-ice** [comment]
解决了，前后端端口换一下就好了

**Comment by jlau-ice** [comment]
还有一个小问题，开发一个端口的情况下，视觉好像不行，使用内网是正常的

![Image](https://github.com/user-attachments/assets/8b489bd2-1a58-4362-a71d-d5639c1ec08a)

使用外网就无法解析，具体错误是。
```
250625 16:49:41[0.5.8-SiFuDiV3noll][core.providers.asr.base]-INFO-识别文本: 看看这是什么。😔
250625 16:49:42[0.5.8-SiFuDiV3noll][core.providers.intent.intent_llm.intent_llm]-INFO-llm 识别到意图: self_camera_take_photo, 参数: {'question': '看看这是什么。'}
250625 16:49:42[0.5.8-SiFuDiV3noll][core.handle.mcpHandle]-INFO-发送客户端mcp工具调用请求: self.camera.take_photo，参数: {"question": "\u770b\u770b\u8fd9\u662f\u4ec0\u4e48\u3002"}
250625 16:49:42[0.5.8-SiFuDiV3noll][core.handle.mcpHandle]-INFO-成功发送MCP消息: {"type": "mcp", "payload": {"jsonrpc": "2.0", "id": 3, "method": "tools/call", "params": {"name": "self.camera.take_photo", "arguments": {"question": "\u770b\u770b\u8fd9\u662f\u4ec0\u4e48\u3002"}}}}
250625 16:49:48[0.5.8-SiFuDiV3noll][core.handle.textHandle]-INFO-收到mcp消息：{"session_id":"bcf95196-14ad-4319-837a-dbad7f363ca1","type":"mcp","payload":{"jsonrpc":"2.0","id":2,"result":{"content":[{"type":"text","text":"{\"success\": false, \"message\": \"Failed to connect to explain URL\"}"}],"isError":false}}}
250625 16:49:48[0.5.8-SiFuDiV3noll][core.handle.mcpHandle]-INFO-处理MCP消息: {'jsonrpc': '2.0', 'id': 2, 'result': {'content': [{'type': 'text', 'text': '{"success": false, "message": "Failed to connect to explain URL"}'}], 'isError': False}}
250625 16:49:48[0.5.8-SiFuDiV3noll][core.handle.mcpHandle]-INFO-客户端mcp工具调用 self.camera.take_photo 成功，原始结果: {'content': [{'type': 'text', 'text': '{"success": false, "message": "Failed to connect to explain URL"}'}], 'isError': False}
250625 16:49:49[0.5.8-SiFuDiV3noll][core.handle.sendAudioHandle]-INFO-发送音频消息: SentenceType.MIDDLE, 看起来我们遇到了一些问题
250625 16:49:49[0.5.8-SiFuDiV3noll][core.handle.sendAudioHandle]-INFO-发送第一段语音: 看起来我们遇到了一些问题
250625 16:49:51[0.5.8-SiFuDiV3noll][core.handle.textHandle]-INFO-收到abort消息：{"session_id":"bcf95196-14ad-4319-837a-dbad7f363ca1","type":"abort"}
250625 16:49:51[0.5.8-SiFuDiV3noll][core.handle.abortHandle]-INFO-Abort message received
250625 16:49:51[0.5.8-SiFuDiV3noll][core.handle.abortHandle]-INFO-Abort message received-end
250625 16:49:51[0.5.8-SiFuDiV3noll][core.handle.textHandle]-INFO-收到listen消息：{"session_id":"bcf95196-14ad-4319-837a-dbad7f363ca1","type":"listen","state":"start","mode":"auto"}
```

**Comment by openrz** [comment]
在你的.config.yaml配置文件，修改`vision_explain`成公网地址就行了，你现在应该是默认的，或者内网的

**Comment by jlau-ice** [comment]
解决了，真的是笑死了，之前的进程没杀死，导致用的一直都是之前的，我说咋改都不生效呢。
怎么发现的，我把服务停了，发现还能说话，见鬼了，查端口也查不到。[捂脸][捂脸]
```
root@dell-PowerEdge-T550:/data1/github/xiaozhi-esp32-server/main/xiaozhi-server# sudo netstat -tunlp | grep '(:8000\|:8003)'
root@dell-PowerEdge-T550:/data1/github/xiaozhi-esp32-server/main/xiaozhi-server# curl 127.0.0.1:8000
Server is running
root@dell-PowerEdge-T550:/data1/github/xiaozhi-esp32-server/main/xiaozhi-server# curl 127.0.0.1:8003
404: Not Foundroot@dell-PowerEdge-T550:/data1/github/xiaozhi-esp32-server/main/xiaozhi-server# 
```

**Comment by AlphaCato** [comment]
大佬，可以参考一下你xiaozhi-esp32-server那段的docker compose吗？我这边也是公网部署，开放端口是8081和8083，8000和8003没有开放端口，这段compose会导致server启动失败，不知道什么问题，我的compose如下：

version: '3'
services:
  # Server模块
  xiaozhi-esp32-server:
    image: ghcr.nju.edu.cn/xinnan-tech/xiaozhi-esp32-server:server_latest
    container_name: xiaozhi-esp32-server
    depends_on:
      - xiaozhi-esp32-server-db
      - xiaozhi-esp32-server-redis
    restart: always
    networks:
      - default
    ports:
      # ws服务端
      - "8000:8000"
      # http服务的端口，用于视觉分析接口
      - "8003:8003"
    security_opt:
      - seccomp:unconfined
    environment:
      - TZ=Asia/Shanghai
    volumes:
      # 配置文件目录
      - ./data:/opt/xiaozhi-esp32-server/data
      # 模型文件挂接，很重要
      - ./models/SenseVoiceSmall/model.pt:/opt/xiaozhi-esp32-server/models/SenseVoiceSmall/model.pt

**Comment by AlphaCato** [comment]
附上命令行输入docker logs -f xiaozhi-esp32-server时的报错提示：
EOFError: stream ends after 0 bytes, before end of line

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/websockets/server.py", line 562, in parse
    request = yield from Request.parse(
  File "/usr/local/lib/python3.10/site-packages/websockets/http11.py", line 140, in parse
    raise EOFError("connection closed while reading HTTP request line") from exc
EOFError: connection closed while reading HTTP request line

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/websockets/asyncio/server.py", line 354, in conn_handler
    await connection.handshake(
  File "/usr/local/lib/python3.10/site-packages/websockets/asyncio/server.py", line 205, in handshake
    raise self.protocol.handshake_exc
websockets.exceptions.InvalidMessage: did not receive a valid HTTP request

**Comment by jlau-ice** [comment]
> 大佬，可以参考一下你xiaozhi-esp32-server那段的docker compose吗？我这边也是公网部署，开放端口是8081和8083，8000和8003没有开放端口，这段compose会导致server启动失败，不知道什么问题，我的compose如下：
> 
> version: '3' services:
> 
> # Server模块
> xiaozhi-esp32-server: image: ghcr.nju.edu.cn/xinnan-tech/xiaozhi-esp32-server:server_latest container_name: xiaozhi-esp32-server depends_on: - xiaozhi-esp32-server-db - xiaozhi-esp32-server-redis restart: always networks: - default ports: # ws服务端 - "8000:8000" # http服务的端口，用于视觉分析接口 - "8003:8003" security_opt: - seccomp:unconfined environment: - TZ=Asia/Shanghai volumes: # 配置文件目录 - ./data:/opt/xiaozhi-esp32-server/data # 模型文件挂接，很重要 - ./models/SenseVoiceSmall/model.pt:/opt/xiaozhi-esp32-server/models/SenseVoiceSmall/model.pt

我的是这样的，这个大概是3个月前部署的了，后面没有更新，不知道什么情况，我的有个端口呗占用了好像，你需要注意一下，我的端口不太一样，nginx 配置也在下面，python 端没打镜像，源码运行的。外网开放了一个端口就行了，好像是 8004 nginx 的地址。希望这些对你有帮助

```yml
## docker 安装前后端 + 数据库 + redis
services:
  web:
    image: nginx:latest
    container_name: xiaozhi-web
    ports:
      - "8004:8004"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/dist:/usr/share/nginx/html
    depends_on:
      - server
    restart: always
    networks:
      - xiaozhi-net
      
  server:
    image: openjdk:21-jdk
    container_name: xiaozhi-server
    volumes:
      - ./server/xiaozhi-esp32-api.jar:/app.jar
      - ./server/logs:/logs
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "8001:8002"
    entrypoint:
      - /bin/sh
      - -c
      - |
        mkdir -p /logs && \
        java -jar app.jar | tee /logs/server.log
    restart: always
    networks:
      - xiaozhi-net

  redis:
    image: redis:latest
    container_name: xiaozhi-redis
    ports:
      - "6381:6379"
    volumes:
      - ./redis/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /usr/local/etc/redis/redis.conf
    restart: always
    networks:
      - xiaozhi-net

  mysql:
    image: mysql8:latest
    container_name: xiaozhi-mysql
    ports:
      - "3309:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "sxkj0818web"
    volumes:

      - ./mysql/data:/var/lib/mysql
      - ./mysql/conf/my.cnf:/etc/my.cnf
    restart: always
    networks:
      - xiaozhi-net

networks:
  xiaozhi-net:
    external: true
```

```

#user  nobody;
worker_processes  1;
#error_log  logs/error.log;
#error_log  logs/error.log  notice;
#error_log  logs/error.log  info;

#pid        logs/nginx.pid;

events {
    worker_connections  1024;
}


http {
    include       mime.types;
    default_type  application/octet-stream;
    sendfile        on;
    keepalive_timeout  65;
    client_max_body_size 200M;
    server {
        listen       8004;
        listen [::]:8004;
        server_name _;
        location / {
            root   /usr/share/nginx/html;
            index  index.html index.htm;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
            root   html;
        }

        location /xiaozhi/ {
            #set $method $request_method;
            #if ($http_X_HTTP_Method_Override ~* 'PUT|DELETE') {
            #    set $method $http_X_HTTP_Method_Override;
            #}
            #proxy_method $method;
            # proxy_pass http://xiaozhi-server:8004;
            proxy_pass http://192.168.187.166:8001;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        # 转发到xiaozhi-server到websocket
        location /xiaozhi/v1/ {
            proxy_pass http://192.168.187.166:8000;
            proxy_set_header Host $host;
            proxy_cookie_path /xiaozhi/ /;

            # 核心IP转发配置
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;

            # WebSocket支持（保持原有配置）
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";

            # 其他头信息（可选）
            proxy_set_header Referer $http_referer;
            proxy_set_header Cookie $http_cookie;
        }
        # mcp相关请求
        location /mcp/ {
            proxy_pass http://192.168.187.166:8003;
            proxy_set_header   Host   $host;
            proxy_cookie_path /mcp/ /;
            proxy_set_header   Referer $http_referer;
            proxy_set_header   Cookie $http_cookie;

            proxy_connect_timeout 15;
            proxy_send_timeout 15;
            proxy_read_timeout 15;

            proxy_set_header   X-Real-IP  $remote_addr;
            proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
        }
        
    }
}

```
