### ISSUE TITLE
[Bug] HomeAssistant 无法通过 SSL 链接

### ISSUE THREAD

**Issue by olarodes** [xinnan-tech/xiaozhi-esp32-server#429]
## 🐛 问题描述

我的主力 Home Assistant (HA) 实例通过配置文件设置了 SSL 证书，并启用了强制 HTTPS。然而，后端服务与 HA 之间的通信一直报 SSL 错误。我已经多次确认配置，并重新设置了一个反向代理服务器，但问题依然存在。

### 访问方式
- **通过反向代理访问**: `https://hass.xxx.ltd:8123`
- **直接访问 HA**: `https://hass.xxx.ltd:38123`

#### 新设置的反向代理
```
25-03-19 14:50:14 [core.providers.llm.homeassistant.homeassistant] - ERROR - HTTP 请求错误: HTTPSConnectionPool(host='hass.xxx.ltd', port=8123): Max retries exceeded with url: /api/conversation/process (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1007)')))
```

#### 直接使用 HA 的证书管理
```
25-03-19 15:52:41 [core.providers.llm.homeassistant.homeassistant] - ERROR - HTTP 请求错误: HTTPSConnectionPool(host='hass.xxx.ltd', port=38123): Max retries exceeded with url: /api/conversation/process (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f28f6075fc0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

## 其他信息
- 浏览器可以正常访问上述两个 URL，说明证书和网络配置在客户端层面没有问题。
- 启用了备用的 HA 实例，未开启强制 HTTPS，后端与 HA 的对话代理服务通信正常。

## 尝试过的排查步骤
1. **检查证书有效期**: 确保证书未过期，并重新生成或更新证书。

<img width="461" alt="Image" src="https://github.com/user-attachments/assets/ab60cdd3-3658-4c66-b29d-a4a68d4a7bdc" />

2. **检查端口配置**: 确认 HA 实例的端口 38123 是否已正确开放，并检查防火墙规则。

确认路由器开放 38123，并正确转发到 HA 内网 IP 的 8123 端口，浏览器内外网均能访问。

3. **检查反向代理配置**: 确保反向代理的配置正确，特别是 SSL 证书的路径和端口转发规则。

确认设置无误，浏览器内外网均能访问。

4. **查看 HA 日志**: 检查 HA 的日志文件，获取更多关于连接被拒绝的详细信息。希望这些信息能帮助您更快地定位和解决问题。如果问题仍然存在，建议提供更多详细的配置信息和日志内容，以便进一步分析。

没找到相关报错的日志

**Comment by olarodes** [comment]
## 补充说明

在之前的反馈中，我提到主力 Home Assistant (HA) 实例在配置了 SSL 证书并启用强制 HTTPS 后，后端服务与 HA 之间的通信出现 SSL 错误。经过进一步排查，我发现以下情况：

- **备用 HA 实例成功使用 SSL**：将备用的 HA 实例配置反向代理后，后端服务可以通过 SSL 链接正常访问，未出现任何错误。
- **主力 HA 实例问题依然存在**：尽管浏览器可以正常访问主力 HA 实例的反向代理和直接链接，但后端服务仍然报 SSL 错误。

### 关键区别
问题可能与是否使用 HA 的 `configuration.yaml` 配置证书有关。

## 继续排查步骤

1. **主力 HA 实例取消配置文件中 SSL 证书的配置**: 使用反代进行连接

仍旧无法正常工作，报错如下：

```
25-03-19 16:34:51[core.providers.llm.homeassistant.homeassistant] - ERROR - HTTP 请求错误: HTTPSConnectionPool(host='hass.xxx.ltd', port=8123): Max retries exceeded with url: /api/conversation/process (Caused by SSLError(SSLError(1, '[SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:1007)')))
```

2. **更改反代的 HTTP 版本**:  从 1.1 改成了 1.0

问题依旧，报错如上。

**Comment by CaixyPromise** [comment]
这个可能会我之前配置的HA的反向代理的问题一样。HA是默认禁止反向代理的。

## 解决方法如下
1. 配置一下HA的configuration.yml。可以在HACS里安装`File Editor`编辑`configuration.yml`
2. 写入下面的配置
```yaml
http:
  use_x_forwarded_for: true # 允许反向代理
  trusted_proxies:
    - 127.0.0.1# 填写可信的代理地址来源
  # 可以补充的内容，但是我自己没有用，我本地HA用http，公网反向代理使用https反向代理
  ssl_certificate: /ssl/fullchain.pem # 你的ssl证书
  ssl_key: /ssl/privkey.pem # 你的ssl证书匹配的私钥文件
  # 以下是可选的，但建议暴露在公网时添加上
  ip_ban_enabled: true # 禁用Ip
  login_attempts_threshold: 5 # 暴力破解尝试次数
```
3. `CTRL` + `S`保存文件
4. 开发者工具，`检查配置` -> `重新加载所有YAML配置`

尝试一下，有问题随时评论回复哈~
