### ISSUE TITLE
[Feature] 能否开发Ali 百炼的 dashscope SDK 接入 LLM

### ISSUE THREAD

**Issue by olarodes** [xinnan-tech/xiaozhi-esp32-server#444]
## 🚀 需求描述
希望为 AliLLM 模块新增 `type: dashscope` 接入类型，以便开发者能直接通过阿里云 Dashscope SDK 调用百炼平台的应用（基础模型加入 RAG、长期记忆、联网搜索等功能）。当前仅支持 OpenAI 兼容接口调用 AliLLM，无法完整使用百炼平台的全部能力。

## 🎯 解决方案
1. **新增 Dashscope 接入类型**
   在 `providers/llm` 中新增 `dashscope` 类，继承基础 LLM 接口，实现以下核心功能：
   - 兼容 Dashscope SDK 的认证方式（API Key + App ID验证）
   - 与兼容 OpenAI 接口不一样的默认 base_url
   - 支持百炼平台特有的参数传递
   - 处理 Dashscope 的响应格式与项目现有结构的兼容性

2. **配置层扩展**
   在 `config.yaml` 中新增 `dashscope` 类型的配置模板，允许用户通过 `type: dashscope` 声明接入方式，并配置相关参数：

  ```
  LLM:
    AliLLM:
      type: dashscope
      base_url: https://dashscope.aliyuncs.com/api/v1/   #公网节点
      app_id: aabbccdd
      api_key: 你的deepseek web key
  ```

## 📝 备选方案
**开发混合模式**
   通过 `type: dashscope_openai` 实现混合协议支持，但会增加接口复杂度。百炼平台特有的参数传递就不适用。

## 📋 其他信息
- 阿里云百炼平台文档：[模型服务 API 文档](https://help.aliyun.com/zh/dashscope/developer-reference)
- 需要特别关注 Dashscope 的流式响应格式与 OpenAI 的差异
- 建议优先实现聊天补全（/v1/chat/completions）接口的兼容
