### ISSUE TITLE
[Bug] 无法使用TTS302AI

### ISSUE THREAD

**Issue by ASARobotics** [xinnan-tech/xiaozhi-esp32-server#733]
## 🐛 问题描述
使用TTS302AI作为TTS provider后，出现TTS 任务出错

## 🔍 复现步骤

1. 于config.yaml输入TTS320AI的config
2. 在config.yaml中，于selected module分项上更改TTS: TTS320AI
3. 使用terminal運行app.py
4. 于test.html中连接server，并发送文本消息
5. 看到错误

## 🤔 预期行为
TTS成功生成audio file

## 😯 截图
Error Code:

![Image](https://github.com/user-attachments/assets/0ddffede-caaf-4aab-a77f-9f783bfb0fbf)

TTS configuration:

![Image](https://github.com/user-attachments/assets/a7df65bb-ee93-4b51-8b5d-7caf18a1442c)

## 🖥️ 环境信息
- 操作系统: Ubuntu 18/04
- 浏览器: Chrome
- 项目版本: v0.2.1(latest)
- Python版本: 3.10.13
- Jdk版本：openjdk 13.0.7 2021-04-20
- Nodejs版本：v22.14.0

**Comment by openrz** [comment]
TTS302AI正确原版的如下，但是你好像是把type改成了`minimax`
```
  TTS302AI:
    # 302AI语音合成服务，需要先在302平台创建账户充值，并获取密钥信息
    # 获取api_keyn路径：https://dash.302.ai/apis/list
    # 价格，$35/百万字符。火山原版¥450元/百万字符
    type: doubao
    api_url: https://api.302ai.cn/doubao/tts_hd
    authorization: "Bearer "
    # 湾湾小何音色
    voice: "zh_female_wanwanxiaohe_moon_bigtts"
    output_dir: tmp/
    access_token: "你的302API密钥"
```
