### ISSUE TITLE
悬赏，300元，使用Dify、Coze的同时，支持functioncall

### ISSUE THREAD

**Issue by manicwy** [xinnan-tech/xiaozhi-esp32-server#746]
intent_llm已经配置的是ChatGLMLLM，貌似新版本更新后，只要LLM设置的是DifyLLM，意图识别和插件功能就失效了

**Comment by openrz** [comment]
目前使用Dify和Coze，意图识别只能选：nointent、intent_llm两个。不能选function_call。这块后期会修复，如果有大神出手，会加快这块的实现。

**Comment by 30763880** [comment]
当前结论是什么？服务端配置Dify中的工作流，无法实现接入嘛？？？

**Comment by dlutwuwei** [comment]
在 Dify 上为智能助手提供了 Function calling（函数调用）和 ReAct 两种推理模式。已支持 Function Call 的模型系列如 gpt-3.5/gpt-4 拥有效果更佳、更稳定的表现，尚未支持 Function calling 的模型系列，我们支持了 ReAct 推理框架实现类似的效果。

**Comment by chubbyerror** [comment]
Dify可以采用CHATFLOW的方式对应functioncall功能，附件是一个简单的对应了你好和再见的CHATFLOW导出的DSL文件，导入后可作为参考。

[测试机器人.zip](https://github.com/user-attachments/files/20602756/default.zip)

当然这并不能算作解决方案，只是一个临时的处理手段。
如果不方便下载，文件本身是很简单的一段yaml脚本，内如如下：
```yaml
app:
  description: ''
  icon: woman
  icon_background: '#E0F2FE'
  mode: advanced-chat
  name: 测试机器人
  use_icon_as_answer_icon: false
kind: app
version: 0.1.5
workflow:
  conversation_variables: []
  environment_variables: []
  features:
    file_upload:
      allowed_file_extensions:
      - .JPG
      - .JPEG
      - .PNG
      - .GIF
      - .WEBP
      - .SVG
      allowed_file_types:
      - image
      allowed_file_upload_methods:
      - local_file
      - remote_url
      enabled: false
      fileUploadConfig:
        audio_file_size_limit: 50
        batch_count_limit: 5
        file_size_limit: 15
        image_file_size_limit: 10
        video_file_size_limit: 100
        workflow_file_upload_limit: 10
      image:
        enabled: false
        number_limits: 3
        transfer_methods:
        - local_file
        - remote_url
      number_limits: 3
    opening_statement: ''
    retriever_resource:
      enabled: false
    sensitive_word_avoidance:
      enabled: false
    speech_to_text:
      enabled: false
    suggested_questions: []
    suggested_questions_after_answer:
      enabled: false
    text_to_speech:
      autoPlay: enabled
      enabled: false
      language: ''
      voice: ''
  graph:
    edges:
    - data:
        sourceType: knowledge-retrieval
        targetType: llm
      id: 1711528915811-1711528917469
      source: '1711528915811'
      sourceHandle: source
      target: '1711528917469'
      targetHandle: target
      type: custom
    - data:
        sourceType: llm
        targetType: answer
      id: 1711528917469-1711528919501
      source: '1711528917469'
      sourceHandle: source
      target: '1711528919501'
      targetHandle: target
      type: custom
    - data:
        isInIteration: false
        sourceType: start
        targetType: if-else
      id: 1711528914102-source-1749098580632-target
      source: '1711528914102'
      sourceHandle: source
      target: '1749098580632'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: if-else
        targetType: knowledge-retrieval
      id: 1749098580632-false-1711528915811-target
      source: '1749098580632'
      sourceHandle: 'false'
      target: '1711528915811'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: if-else
        targetType: answer
      id: 1749098580632-true-1749098620015-target
      source: '1749098580632'
      sourceHandle: 'true'
      target: '1749098620015'
      targetHandle: target
      type: custom
      zIndex: 0
    - data:
        isInIteration: false
        sourceType: if-else
        targetType: answer
      id: 1749098580632-301e2b4c-8d3b-4493-80e1-1c697ce03dab-1749098721104-target
      source: '1749098580632'
      sourceHandle: 301e2b4c-8d3b-4493-80e1-1c697ce03dab
      target: '1749098721104'
      targetHandle: target
      type: custom
      zIndex: 0
    nodes:
    - data:
        desc: ''
        selected: false
        title: Start
        type: start
        variables: []
      height: 54
      id: '1711528914102'
      position:
        x: 79.5
        y: 2634.5
      positionAbsolute:
        x: 79.5
        y: 2634.5
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        dataset_ids:
        - ed78f5d1-9427-4226-8826-110ab01c2ca2
        desc: Allows you to query text content related to user questions from the
          Knowledge
        multiple_retrieval_config:
          reranking_enable: false
          reranking_mode: reranking_model
          reranking_model:
            model: BAAI/bge-reranker-v2-m3
            provider: huggingface_tei
          score_threshold: null
          top_k: 4
          weights:
            keyword_setting:
              keyword_weight: 1
            vector_setting:
              embedding_model_name: bge-large
              embedding_provider_name: ollama
              vector_weight: 0
        query_variable_selector:
        - sys
        - query
        retrieval_mode: multiple
        selected: false
        single_retrieval_config:
          model:
            completion_params:
              frequency_penalty: 0
              max_tokens: 512
              presence_penalty: 0
              temperature: 0
              top_p: 1
            mode: chat
            name: gpt-3.5-turbo
            provider: openai
        title: Knowledge Retrieval
        type: knowledge-retrieval
      dragging: false
      height: 152
      id: '1711528915811'
      position:
        x: 685.6074530285271
        y: 2634.5
      positionAbsolute:
        x: 685.6074530285271
        y: 2634.5
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        context:
          enabled: true
          variable_selector:
          - '1711528915811'
          - result
        desc: Invoking large language models to answer questions or process natural
          language
        memory:
          query_prompt_template: '{{#1711528915811.result#}}{{#sys.query#}}'
          role_prefix:
            assistant: ''
            user: ''
          window:
            enabled: false
            size: 50
        model:
          completion_params:
            frequency_penalty: 0
            max_tokens: 512
            presence_penalty: 0
            temperature: 0.7
            top_p: 1
          mode: chat
          name: glm4:latest
          provider: openai_api_compatible
        prompt_template:
        - id: 7ec7b3dc-1a29-4047-88a0-c7d111e6699f
          role: system
          text: "```xml\n<task>\n    <description>\n        你是一个根据知识库提供信息的智能对话助手，你更喜欢说中文。\n\
            \        当用户跟你说再见或其他分别的话语时候，你也要跟用户再见\n    </description>\n    <instructions>\n\
            \        <step>1.</step>\n        <sub-step>当用户发起对话时，首先确认用户的语言偏好为中文。</sub-step>\n\
            \        <step>2.</step>\n        <sub-step>根据用户提供的信息或问题，从知识库中检索相关信息。</sub-step>\n\
            \        <step>3.</step>\n        <sub-step>使用中文回复用户的问题或提供信息，确保回答准确、简洁且符合用户需求。</sub-step>\n\
            \        <step>4.</step>\n        <sub-step>当用户说再见或其他分别的话语时，应礼貌地回应“再见”。</sub-step>\n\
            \        <note>输出内容中不应包含任何XML标签。</note>\n    </instructions>\n    <examples>\n\
            \        <example>\n            <input>User: 你好，我想了解一下中国的历史。</input>\n\
            \            <output>你好！中国有着悠久的历史，您可以具体想了解哪个时期或事件呢？</output>\n       \
            \ </example>\n        <example>\n            <input>User: 再见。</input>\n\
            \            <output>再见！祝您有一个愉快的一天！</output>\n        </example>\n   \
            \     <example>\n            <input>User: 我想查询一下北京的天气预报。</input>\n   \
            \         <output>好的，请稍等。我正在为您查询北京的天气预报...</output>\n        </example>\n\
            \    </examples>\n</task>\n```"
        selected: false
        title: LLM
        type: llm
        variables: []
        vision:
          enabled: false
      height: 158
      id: '1711528917469'
      position:
        x: 1012.5
        y: 2634.5
      positionAbsolute:
        x: 1012.5
        y: 2634.5
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: '{{#1711528917469.text#}}'
        desc: ''
        selected: false
        title: Answer
        type: answer
        variables: []
      height: 103
      id: '1711528919501'
      position:
        x: 1321.5
        y: 2634.5
      positionAbsolute:
        x: 1321.5
        y: 2634.5
      selected: true
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        cases:
        - case_id: 'true'
          conditions:
          - comparison_operator: contains
            id: 70d17528-ea13-4552-b15b-7f1e01ecaa69
            value: 你好呀
            varType: string
            variable_selector:
            - sys
            - query
          id: 'true'
          logical_operator: or
        - case_id: 301e2b4c-8d3b-4493-80e1-1c697ce03dab
          conditions:
          - comparison_operator: contains
            id: c4e2bf63-82c2-434a-b1a8-bc2ac138cfc2
            value: 再见
            varType: string
            variable_selector:
            - sys
            - query
          logical_operator: and
        desc: ''
        selected: false
        title: 条件分支
        type: if-else
      height: 174
      id: '1749098580632'
      position:
        x: 391.60745302852706
        y: 2506.5
      positionAbsolute:
        x: 391.60745302852706
        y: 2506.5
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: 你好呀
        desc: ''
        selected: false
        title: 直接回复 2
        type: answer
        variables: []
      height: 100
      id: '1749098620015'
      position:
        x: 728.6074530285272
        y: 2313.5
      positionAbsolute:
        x: 728.6074530285272
        y: 2313.5
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    - data:
        answer: '<tool_call>

          {

          "name": "handle_exit_intent",

          "arguments": {

          "say_goodbye": "再见，祝您生活愉快！"

          }

          }

          </tool_call>

          '
        desc: ''
        selected: false
        title: 直接回复 3
        type: answer
        variables: []
      height: 148
      id: '1749098721104'
      position:
        x: 721.6074530285272
        y: 2446.5
      positionAbsolute:
        x: 721.6074530285272
        y: 2446.5
      selected: false
      sourcePosition: right
      targetPosition: left
      type: custom
      width: 244
    viewport:
      x: 48.39254697147271
      y: -2178.5
      zoom: 1
```
复制信息后保存为任意名yaml文件即可导入Dify
