### ISSUE TITLE
原有config.yaml配置文件中部分参数，在全功能版本内如何设置

### ISSUE THREAD

**Issue by likeaturtle** [xinnan-tech/xiaozhi-esp32-server#808]
如下图，原有config.yaml配置文件中部分参数，在全功能版本内如何设置？
![Image](https://github.com/user-attachments/assets/d479a12d-0820-4427-ae9c-870b15b05dca)

**Comment by openrz** [comment]
这些配置都不需要了，所有配置通过智控台获取
```
manager-api:
  # 你的manager-api的地址，最好使用局域网ip
  url: http://127.0.0.1:8002/xiaozhi
  # 你的manager-api的token，就是刚才复制出来的server.secret
  secret: 你的server.secret值
```
