### ISSUE TITLE
最新release下如何通过智控台修改xiaozhi-server端口号

### ISSUE THREAD

**Issue by likeaturtle** [xinnan-tech/xiaozhi-esp32-server#945]
全模块本地部署，希望把app.py启动后的端口号从8000设置为8333，如何在新版智控台的server.websocket下设置？云服务器通过nginx反代到了域名上，是填写域名还是云服务器内网IP？

**Comment by openrz** [comment]
0.3.10版本，端口号不再从智控台下发，而是在main/xiaozhi-server/config_from_api.yaml文件配置独立端口号

```
server:
  ip: 0.0.0.0
  port: 8000
manager-api:
  # 你的manager-api的地址，最好使用局域网ip
  url: http://127.0.0.1:8002/xiaozhi
  # 你的manager-api的token，就是刚才复制出来的server.secret
  secret: 你的server.secret值
```

这样做的好处是，一个智控台可以管理好几个Server，每个Server拥有独立端口，可以在一台超级计算机中部署多个Server。
